<!doctype html><html lang="en-US"><!--  --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- / -->
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">  <link media="all" href="../../wp-content/cache/autoptimize/4/css/autoptimize_dc56928889f08ceb40a4520f8ece953b.css" rel="stylesheet" /><title>How to avoid throwing vexing exceptions &#8211; free-tor-game.com</title> <script>MathJax = {
  tex: {
    inlineMath: [['$','$'],['\\(','\\)']], 
    processEscapes: true
  },
  options: {
    ignoreHtmlClass: 'tex2jax_ignore|editor-rich-text'
  }
};</script> <link rel='dns-prefetch' href='http://cdn.jsdelivr.net/' /><link rel='dns-prefetch' href='http://cdnjs.cloudflare.com/' /><link rel='dns-prefetch' href='http://stackpath.bootstrapcdn.com/' /><link rel='dns-prefetch' href='http://s.w.org/' /><link rel='stylesheet' id='highlight-css'  href='../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/vs2015.min40df.css?ver=5.6' type='text/css' media='all' /><link rel='stylesheet' id='bootstrap-css'  href='../../../cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.mina352.css?ver=4.1.3' type='text/css' media='all' /><link rel='stylesheet' id='icons-css'  href='../../../stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min40df.css?ver=5.6' type='text/css' media='all' /> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.minb8ff.js?ver=1.12.4' id='jquery-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.minc9a3.js?ver=11.2.0' id='highlight-js'></script>            <script>hljs.highlightAll();</script> <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1731162805004860" crossorigin="anonymous"></script></head><body class="software-template-default single single-software postid-1079013 no-sidebar"><div id="page" class="site"> <a class="skip-link screen-reader-text" href="#content">Skip to content</a><header id="topnav" class="sticky-top"><nav class="navbar navbar-expand-md navbar-light bg-light" role="navigation"> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-primary" aria-controls="navbar-primary" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button> <a class="navbar-brand" href="#">free-tor-game.com</a><div id="navbar-primary" class="collapse navbar-collapse"><ul id="menu-primary-top-menu" class="nav navbar-nav"><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-192" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children dropdown menu-item-192 nav-item"><a title="Tools" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle nav-link" id="menu-item-dropdown-192">Tools</a><ul class="dropdown-menu" aria-labelledby="menu-item-dropdown-192" role="menu"><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-193" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-193 nav-item"><a title="ARFCN-Frequency Converter" href="../../3gpp-arfcn-frequency-converter/" class="dropdown-item">ARFCN-Frequency Converter</a></li></ul></li><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-2301" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2301 nav-item"><a title="Contact Us" href="../../contact/" class="nav-link">Contact Us</a></li></ul></div></nav></header><div id="content" class="site-content"><div id="primary" class="content-area"><main id="main" class="site-main"><div id="main-container" class="container"><div id="main-row" class="row"><div id="main-col" class="col-12"><article id="post-1079013" class="post-1079013 software type-software status-publish hentry category-software tag-exceptions"><div class="row"><div class="col-12 col-md-8"><header class="entry-header"><h1 class="entry-title text-danger">How to avoid throwing vexing exceptions</h1></header><p style='font-size:1.2em'><span class="mr-2 badge badge-success">exceptions</span></p><div class="entry-content"><p>Reading Eric Lippert&#39;s <a href="https://docs.microsoft.com/en-us/archive/blogs/ericlippert/vexing-exceptions" rel="nofollow noreferrer">article on exceptions</a> was definitely an eye opener on how I should approach exceptions, both as the producer and as the consumer. However, I&#39;m still struggling to define a guideline regarding how to avoid throwing vexing exceptions.</p><p>Specifically:</p><ul><li>Suppose you have a Save method that can fail because a) <em>Somebody else modified the record before you</em>, or b) <em>The value you&#39;re trying to create already exists</em>. These conditions are to be expected and not exceptional, so instead of throwing an exception you decide to create a Try version of your method, TrySave, which returns a boolean indicating if the save succeeded. But if it fails, how will the consumer know what was the problem? Or would it be best to return an enum indicating the result, kind of Ok/RecordAlreadyModified/ValueAlreadyExists? With integer.TryParse this problem doesn&#39;t exist, since there&#39;s only one reason the method can fail.</li><li>Is the previous example really a vexing situation? Or would throwing an exception in this case be the preferred way? I know that&#39;s how it&#39;s done in most libraries and frameworks, including the Entity framework.</li><li>How do you decide when to create a Try version of your method vs. providing some way to test beforehand if the method will work or not? I&#39;m currently following these guidelines:<ul><li>If there is the chance of a race condition, then create a Try version. This prevents the need for the consumer to catch an exogenous exception. For example, in the Save method described before.</li><li>If the method to test the condition pretty much would do all that the original method does, then create a Try version. For example, integer.TryParse().</li><li>In any other case, create a method to test the condition.</li></ul></li></ul></div>     <div id="comments" class="comments-area"><div class="row"><div class="col-12"><div class="mt-3 border-bottom border-success"><h4 class="text-success"><i class='fa fa-check-circle text-success mr-3'></i><span>Best Answer</span></h4></div><div class='bg-transparent mb-3'><blockquote><p>Suppose you have a Save method that can fail because a) Somebody else modified the record before you, or b) The value you&#39;re trying to create already exists. These conditions are to be expected and not exceptional, so instead of throwing an exception you decide to create a Try version of your method, TrySave, which returns a boolean indicating if the save succeeded. But if it fails, how will the consumer know what was the problem?</p></blockquote><p>Good question.</p><p>The first question that comes to my mind is: <em>if the data is already there then in what sense did the save <strong>fail</strong>?</em> It sure sounds like it succeeded to me. But let&#39;s assume for the sake of argument that you really do have many different reasons why an operation can fail.</p><p>The second question that comes to my mind is: <em>is the information you wish to return to the user <strong>actionable</strong>?</em> That is, are they going to make some decision based on that information?</p><p>When the &#34;check engine&#34; light comes on, I open up the hood, verify that there is an engine in my car that is not on fire, and take it to the garage. Of course at the garage they have all kinds of special purpose diagnostic equipment that tells them why the check engine light is on, but from <em>my</em> perspective, the warning system is well designed. I do not care whether the problem is because the oxygen sensor is recording an abnormal level of oxygen in the combustion chamber, or because the idle speed detector is unplugged, or whatever. I&#39;m going to take the same action, namely, <em>let someone else figure this out</em>.</p><p>Does the caller care why the save failed? Are they going to do anything about it, other than either give up or try again?</p><p>Let&#39;s assume for the sake of argument that the caller really is going to take different actions depending on the reason why the operation failed.</p><p>The third question that comes to mind is: <em>is the failure mode <strong>exceptional</strong>?</em> I think you might be confusing <em>possible</em> with <em>unexceptional</em>. I would think of two users attempting to modify the same record at the same time as an exceptional-but-possible situation, not a common situation.</p><p>Let&#39;s assume for the sake of argument that it is unexceptional.</p><p>The fourth question that comes to mind is: <em>is there a way to reliably detect the bad situation ahead of time?</em></p><p>If the bad situation is in my &#34;exogenous&#34; bucket, then, no. There&#39;s no way to reliably say &#34;did another user modify this record?&#34; because they might modify it <em>after you ask the question</em>. The answer is <em>stale</em> as soon as it is produced.</p><p>The fifth question that comes to mind is: <em>is there a way to design the API so that the bad situation can be prevented?</em></p><p>For example, you could make the &#34;save&#34; operation require two steps. Step one: acquire a lock on the record being modified. That operation either succeeds or fails and so can return a Boolean. The caller can then have a policy about how to deal with failure: wait a while and try again, give up, whatever.  Step two: once the lock is acquired, do the save and release the lock. Now the save <em>always succeeds</em> and so there is no need to worry about any kind of error handling. If the save fails, that is truly exceptional.</p></div></div><div class="col-4"></div></div></div></div><div class="col-12 col-md-4"> <ins class="adsbygoogle"
 style="display:block"
 data-ad-client="ca-pub-1731162805004860"
 data-ad-slot="1340983829"
 data-ad-format="auto"
 data-full-width-responsive="true"></ins>   <div class='mt-3 ml-4 border-bottom border-success'><h6><span>Related Question</span></h6></div><ul class='list-group list-group-flush'><li class="list-group-item"><a href='../c-how-to-treat-unhandled-exceptions-terminate-the-application-vs-keep-it-alive/'>C# &#8211; How to treat unhandled exceptions? (Terminate the application vs. Keep it alive)</a></li><li class="list-group-item"><a href='../boneheaded-exceptions-not-be-caught-especially-in-server-code/'>&#8216;boneheaded&#8217; exceptions not be caught, especially in server code</a></li><li class="list-group-item"><a href='../c-throwing-exception-from-constructor/'>C# &#8211; Throwing exception from constructor</a></li></ul></div></div><footer class="entry-footer"></footer></article></div></div></div></main></div></div><footer id="colophon" class="site-footer"><div class="site-info"></div></footer></div>    <script type='text/javascript' src='../../../cdn.jsdelivr.net/npm/mathjax%403/es5/tex-chtml40df.js?ver=5.6' id='mathjax-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/esm/popper.min43d3.js?ver=1.14.7' id='popper-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min5b31.js?ver=4.3.1' id='bootstrap4-js'></script> <script type='text/javascript' id='itectec-common-js-extra'>var globalObject = {"homeUrl":"https:\/\/free-tor-game.com\/"};</script> <script defer src="../../wp-content/cache/autoptimize/4/js/autoptimize_63b39f43631847816e6b0e70ea726624.js"></script></body></html>