<!doctype html><html lang="en-US"><!--  --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- / -->
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">  <link media="all" href="../../wp-content/cache/autoptimize/4/css/autoptimize_dc56928889f08ceb40a4520f8ece953b.css" rel="stylesheet" /><title>Are there legitimate reasons for returning exception objects instead of throwing them &#8211; free-tor-game.com</title> <script>MathJax = {
  tex: {
    inlineMath: [['$','$'],['\\(','\\)']], 
    processEscapes: true
  },
  options: {
    ignoreHtmlClass: 'tex2jax_ignore|editor-rich-text'
  }
};</script> <link rel='dns-prefetch' href='http://cdn.jsdelivr.net/' /><link rel='dns-prefetch' href='http://cdnjs.cloudflare.com/' /><link rel='dns-prefetch' href='http://stackpath.bootstrapcdn.com/' /><link rel='dns-prefetch' href='http://s.w.org/' /><link rel='stylesheet' id='highlight-css'  href='../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/vs2015.min40df.css?ver=5.6' type='text/css' media='all' /><link rel='stylesheet' id='bootstrap-css'  href='../../../cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.mina352.css?ver=4.1.3' type='text/css' media='all' /><link rel='stylesheet' id='icons-css'  href='../../../stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min40df.css?ver=5.6' type='text/css' media='all' /> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.minb8ff.js?ver=1.12.4' id='jquery-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.minc9a3.js?ver=11.2.0' id='highlight-js'></script>            <script>hljs.highlightAll();</script> <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1731162805004860" crossorigin="anonymous"></script></head><body class="software-template-default single single-software postid-1069911 no-sidebar"><div id="page" class="site"> <a class="skip-link screen-reader-text" href="#content">Skip to content</a><header id="topnav" class="sticky-top"><nav class="navbar navbar-expand-md navbar-light bg-light" role="navigation"> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-primary" aria-controls="navbar-primary" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button> <a class="navbar-brand" href="#">free-tor-game.com</a><div id="navbar-primary" class="collapse navbar-collapse"><ul id="menu-primary-top-menu" class="nav navbar-nav"><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-192" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children dropdown menu-item-192 nav-item"><a title="Tools" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle nav-link" id="menu-item-dropdown-192">Tools</a><ul class="dropdown-menu" aria-labelledby="menu-item-dropdown-192" role="menu"><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-193" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-193 nav-item"><a title="ARFCN-Frequency Converter" href="../../3gpp-arfcn-frequency-converter/" class="dropdown-item">ARFCN-Frequency Converter</a></li></ul></li><li itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement" id="menu-item-2301" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2301 nav-item"><a title="Contact Us" href="../../contact/" class="nav-link">Contact Us</a></li></ul></div></nav></header><div id="content" class="site-content"><div id="primary" class="content-area"><main id="main" class="site-main"><div id="main-container" class="container"><div id="main-row" class="row"><div id="main-col" class="col-12"><article id="post-1069911" class="post-1069911 software type-software status-publish hentry category-software tag-exception-handling tag-exceptions"><div class="row"><div class="col-12 col-md-8"><header class="entry-header"><h1 class="entry-title text-danger">Are there legitimate reasons for returning exception objects instead of throwing them</h1></header><p style='font-size:1.2em'><span class="mr-2 badge badge-success">exception handling</span><span class="mr-2 badge badge-info">exceptions</span></p><div class="entry-content"><p><em>This question is intended to apply to any OO programming language that supports exception handling; I am using C# for illustrative purposes only.</em></p><p>Exceptions are usually intended to be raised when an problem arises that the code cannot immediately handle, and then to be caught in a <code>catch</code> clause in a different location (usually an outer stack frame).</p><p><strong>Q:</strong> Are there any legitimate situations where exceptions are not thrown and caught, but simply returned from a method and then passed around as error objects?</p><p>This question came up for me because .NET 4&#39;s <a href="http://msdn.microsoft.com/en-us/library/dd781657.aspx"><code>System.IObserver&lt;T&gt;.OnError</code> method</a> suggests just that: exceptions being passed around as error objects.</p><p>Let&#39;s look at another scenario, validation. Let&#39;s say I am following conventional wisdom, and that I am therefore distinguishing between an error object type <code>IValidationError</code> and a separate exception type <code>ValidationException</code> that is used to report unexpected errors:</p><pre class="lang-csharp prettyprint-override"><code>partial interface IValidationError { }

abstract partial class ValidationException : System.Exception
{
    public abstract IValidationError[] ValidationErrors { get; }
}
</code></pre><p>(The <a href="http://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.aspx"><code>System.Component.DataAnnotations</code> namespace</a> does something quite similar.)</p><p>These types could be employed as follows:</p><pre class="lang-csharp prettyprint-override"><code>partial interface IFoo { }  // an immutable type

partial interface IFooBuilder  // mutable counterpart to prepare instances of above type
{
    bool IsValid(out IValidationError[] validationErrors);  // true if no validation error occurs
    IFoo Build();  // throws ValidationException if !IsValid(â€¦)
}
</code></pre><p>Now I am wondering, could I not simplify the above to this:</p><pre class="lang-csharp prettyprint-override"><code>partial class ValidationError : System.Exception { }  // = IValidationError + ValidationException

partial interface IFoo { }  // (unchanged)

partial interface IFooBuilder
{
    bool IsValid(out ValidationError[] validationErrors);
    IFoo Build();  // may throw ValidationError or sth. like AggregateException&lt;ValidationError&gt;
}
</code></pre><p><strong>Q:</strong> What are the advantages and disadvantages of these two differing approaches?</p></div>     <div id="comments" class="comments-area"><div class="row"><div class="col-12"><div class="mt-3 border-bottom border-success"><h4 class="text-success"><i class='fa fa-check-circle text-success mr-3'></i><span>Best Answer</span></h4></div><div class='bg-transparent mb-3'><blockquote><p>Are there any legitimate situations where exceptions are not thrown and caught, but simply returned from a method and then passed around as error objects?</p></blockquote><p>If it is never thrown then it&#39;s not an exception. It is an object <code>derived</code> from an Exception class, though it does not follow the behavior. Calling it an Exception is purely semantics at this point, but I see nothing wrong with not throwing it. From my perspective, not throwing an exception is the exact same thing as an inner-function catching it and preventing it from propagating.</p><p><em>Is it valid for a function to return exception objects?</em></p><p>Absolutely. Here is a short list of examples where this may be appropriate:</p><ul><li>An exception factory.</li><li>A context object that reports if there was a previous error as a ready to use exception.</li><li>A function that keeps a previously caught exception.</li><li>A third-party API that creates an exception of an inner type.</li></ul><p><em>Is not throwing it bad?</em></p><p>Throwing an exception is kind of like: &#34;Go to jail. Do not pass Go!&#34; in the board game Monopoly. It tells a compiler to jump over all source code up to the catch without executing any of that source code. It doesn&#39;t have anything to do with errors, reporting or stopping bugs. I like to think of throwing an exception as a &#34;super return&#34; statement for a function. It returns execution of the code to somewhere much higher up than the original caller.</p><p>The important thing here is to understand that the true value of exceptions is in the <code>try/catch</code> pattern, and not the instantiation of the exception object. The exception object is just a state message.</p><p>In your question you seem to be confusing the usage of these two things: a jumping to a handler of the exception, and the error state the exception represents. Just because you took an error state and wrapped it in an exception does not mean you are following the <code>try/catch</code> pattern or its benefits.</p></div></div><div class="col-4"></div></div></div></div><div class="col-12 col-md-4"> <ins class="adsbygoogle"
 style="display:block"
 data-ad-client="ca-pub-1731162805004860"
 data-ad-slot="1340983829"
 data-ad-format="auto"
 data-full-width-responsive="true"></ins>   <div class='mt-3 ml-4 border-bottom border-success'><h6><span>Related Question</span></h6></div><ul class='list-group list-group-flush'><li class="list-group-item"><a href='../c-term-for-the-error-handling-anti-pattern-of-discarding-all-available-info-and-just-returning-failure/'>C++ &#8211;  term for the error-handling anti-pattern of discarding all available info and just returning failure</a></li><li class="list-group-item"><a href='../java-function-returning-true-false-vs-void-when-succeeding-and-throwing-an-exception-when-failing/'>Java &#8211; Function returning true/false vs. void when succeeding and throwing an exception when failing</a></li><li class="list-group-item"><a href='../c-augment-a-thrown-exception-with-some-contextual-information/'>C++ &#8211; Augment a thrown exception with some contextual information</a></li></ul></div></div><footer class="entry-footer"></footer></article></div></div></div></main></div></div><footer id="colophon" class="site-footer"><div class="site-info"></div></footer></div>    <script type='text/javascript' src='../../../cdn.jsdelivr.net/npm/mathjax%403/es5/tex-chtml40df.js?ver=5.6' id='mathjax-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/esm/popper.min43d3.js?ver=1.14.7' id='popper-js'></script> <script type='text/javascript' src='../../../cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min5b31.js?ver=4.3.1' id='bootstrap4-js'></script> <script type='text/javascript' id='itectec-common-js-extra'>var globalObject = {"homeUrl":"https:\/\/free-tor-game.com\/"};</script> <script defer src="../../wp-content/cache/autoptimize/4/js/autoptimize_63b39f43631847816e6b0e70ea726624.js"></script></body></html>